checks:
  php: true

filter:
  paths:
    - "src/*"

tools:
  external_code_coverage:
    timeout: 900    # Timeout in seconds.
    runs: 5         # How many code coverage submissions Scrutinizer will wait

build:
  nodes:
    analysis:
      environment:
        php: 8.0

      tests:
        override:
          - php-scrutinizer-run
