<?php

declare(strict_types=1);

namespace Cycle\ORM\Tests\Functional\Driver\Postgres\Integration\Case8;

// phpcs:ignore
use Cycle\ORM\Tests\Functional\Driver\Common\Integration\Case8\CaseTest as CommonClass;
use Cycle\ORM\Tests\Functional\Driver\Common\Integration\Case8\Entity\Event;

/**
 * @group driver
 * @group driver-postgres
 */
class CaseTest extends CommonClass
{
    public const DRIVER = 'postgres';

    /** UUID below the partition boundary `8000...` => lands in `event_p0`. */
    private const PARENT_LOW = '01000000-0000-7000-8000-000000000000';

    /** UUID at/above the partition boundary `8000...` => lands in `event_p1`. */
    private const PARENT_HIGH = 'f1000000-0000-7000-8000-000000000000';

    /**
     * The whole Case8 behaviour (composite PK + database-generated id, fetched via RETURNING)
     * is exercised against a real RANGE-partitioned table here. `parent_id` (UUID7) is the
     * partition key, therefore it has to be a part of the composite primary key.
     */
    public function testRowsAreRoutedToPartitions(): void
    {
        $low = new Event(self::PARENT_LOW, 'low');
        $high = new Event(self::PARENT_HIGH, 'high');

        $this->save($low, $high);

        // ids were generated by the database even though the insert targets a partitioned table
        $this->assertIsInt($low->id);
        $this->assertIsInt($high->id);

        $db = $this->getDatabase();

        // Each row physically landed in the partition selected by its parent_id.
        $this->assertSame(1, $db->table('event_p0')->select()->where('payload', 'low')->count());
        $this->assertSame(0, $db->table('event_p0')->select()->where('payload', 'high')->count());
        $this->assertSame(1, $db->table('event_p1')->select()->where('payload', 'high')->count());
        $this->assertSame(0, $db->table('event_p1')->select()->where('payload', 'low')->count());

        // ...and they are both visible through the partitioned parent table.
        $this->assertSame(2, $db->table('event')->select()->count());
    }

    public function tearDown(): void
    {
        // Drop the partitioned table (and its partitions + owned sequence) before BaseTest's
        // introspection-based cleanup runs, which does not handle partitioned tables.
        $this->getDatabase()->execute('DROP TABLE IF EXISTS event CASCADE');

        parent::tearDown();
    }

    protected function createEventTable(): void
    {
        $db = $this->getDatabase();

        // RANGE partitioning by the UUID7 partition key. `id` is a bigserial that is part of the
        // composite PK but not the sole key — exactly the scenario discussed for this case.
        $db->execute(
            <<<'SQL'
                CREATE TABLE event (
                    parent_id uuid        NOT NULL,
                    id        bigserial   NOT NULL,
                    payload   varchar(255),
                    PRIMARY KEY (parent_id, id)
                ) PARTITION BY RANGE (parent_id)
                SQL,
        );
        $db->execute(
            "CREATE TABLE event_p0 PARTITION OF event "
            . "FOR VALUES FROM (MINVALUE) TO ('80000000-0000-0000-0000-000000000000')",
        );
        $db->execute(
            "CREATE TABLE event_p1 PARTITION OF event "
            . "FOR VALUES FROM ('80000000-0000-0000-0000-000000000000') TO (MAXVALUE)",
        );
    }
}
