<?php

declare(strict_types=1);

namespace Cycle\ORM\Tests\Functional\Driver\SQLite\Integration\Case8;

// phpcs:ignore
use Cycle\ORM\Tests\Functional\Driver\Common\Integration\Case8\CaseTest as CommonClass;

/**
 * SQLite variant of Case8: a composite primary key whose `id` part is generated by the database.
 *
 * Two things make SQLite different from the Postgres fixture:
 *
 *  1. SQLite has no sequences. The only autoincrementing column is the `rowid` alias, and it
 *     requires a SINGLE-column `INTEGER PRIMARY KEY`. Inside a real composite
 *     `PRIMARY KEY (parent_id, id)` the `id` column is an ordinary one — inserting without it
 *     (or with `NULL`) fails with `NOT NULL constraint failed`, and there is nothing for the
 *     database to generate. The table below therefore keeps `id` as the physical single-column
 *     primary key and expresses the logical composite key as `UNIQUE (parent_id, id)`, which
 *     doubles as the index serving `wherePK()` lookups. The ORM-side schema is unchanged:
 *     `PRIMARY_KEY => ['parentId', 'id']`.
 *  2. Reading the generated value back requires `RETURNING`: {@see \Cycle\ORM\Mapper\DatabaseMapper}
 *     passes `null` as the pk column for a composite key, so the `lastInsertId` fallback in
 *     {@see \Cycle\ORM\Command\Database\Insert::execute()} is unavailable. SQLite supports
 *     `RETURNING` since 3.35.0, and `Cycle\Database\Driver\SQLite\Query\SQLiteInsertQuery`
 *     implements {@see \Cycle\Database\Query\ReturningInterface}.
 *
 * @group driver
 * @group driver-sqlite
 */
class CaseTest extends CommonClass
{
    public const DRIVER = 'sqlite';

    protected function createEventTable(): void
    {
        $this->getDatabase()->execute(
            <<<'SQL'
                CREATE TABLE event (
                    parent_id varchar(36) NOT NULL,
                    id        integer     NOT NULL PRIMARY KEY AUTOINCREMENT,
                    payload   varchar(255),
                    UNIQUE (parent_id, id)
                )
                SQL,
        );
    }
}
