name: Bug Report
description: 🐛 File a bug report
title: "🐛 Some think went wrong"
labels: ["type:bug", "status:to be verified"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    id: search-done
    attributes:
      label: No duplicates 🥲.
      options:
        - label: I have searched for a similar issue in our bug tracker and didn't find any solutions.
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? Please write only in English.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      render: shell
      value: |
        ORM 2.3.4
        PHP 8.2
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        If you know how to reproduce the bug you can
        [do it easily via Pull Request with your Test Case](https://cycle-orm.dev/docs/issue-test-case).
