<?php

declare(strict_types=1);

namespace Cycle\ORM\Tests\Functional\Driver\Common\Integration\Case8;

use Cycle\ORM\Heap\Heap;
use Cycle\ORM\Select;
use Cycle\ORM\Tests\Functional\Driver\Common\BaseTest;
use Cycle\ORM\Tests\Functional\Driver\Common\Integration\Case8\Entity\Event;
use Cycle\ORM\Tests\Functional\Driver\Common\Integration\IntegrationTestTrait;
use Cycle\ORM\Tests\Traits\TableTrait;
use Cycle\ORM\Tests\Util\DontGenerateAttribute;

/**
 * Composite primary key where one part is supplied by the application and the other is generated
 * by the database.
 *
 * # Scenario
 *
 * A partitioning-friendly table:
 *
 *  - `parent_id` — a UUID (UUID7, time-ordered) provided by the application. On the database side
 *    it is the partition key, therefore — by PostgreSQL's rules — it MUST be a part of the primary
 *    key of a partitioned table.
 *  - `id` — generated by the database (`bigserial` / `IDENTITY`). It provides the actual row
 *    uniqueness; `parent_id` only co-locates rows into a partition.
 *
 * The primary key is the composite `(parent_id, id)`. The novelty compared to the other composite
 * PK fixtures (see {@see \Cycle\ORM\Tests\Functional\Driver\Common\Schema\CompositePKTest} where
 * every key part is assigned by the application) is that ONE part of the key is produced by the
 * database during the INSERT and has to be read back into the entity.
 *
 * # How the generated key is read back
 *
 * The `id` field is declared as {@see \Cycle\ORM\Schema\GeneratedField::ON_INSERT} in
 * {@see \Cycle\ORM\SchemaInterface::GENERATED_FIELDS} (see `schema.php`). On INSERT the mapper
 * omits that column and asks the database to return its value:
 *
 *  - {@see \Cycle\ORM\Command\Database\Insert::execute()} appends a `RETURNING` clause for every
 *    `ON_INSERT` field and writes the returned value back into the entity state — this path is
 *    independent of how many columns the primary key has.
 *  - The legacy `lastInsertId` path is only used for a SINGLE-column key:
 *    {@see \Cycle\ORM\Mapper\DatabaseMapper::queueCreate()} passes `null` as the pk column when the
 *    key is composite. So for a composite key the generated value can ONLY be obtained via
 *    `RETURNING`.
 *
 * Therefore this case is bound to drivers that implement
 * {@see \Cycle\Database\Query\ReturningInterface} (PostgreSQL, SQL Server). On MySQL/SQLite the
 * generated `id` of a composite key would not be returned, so the test self-skips in {@see setUp()}.
 *
 * # Mapping gotcha
 *
 * In `schema.php` the keys of {@see \Cycle\ORM\SchemaInterface::PRIMARY_KEY},
 * {@see \Cycle\ORM\SchemaInterface::FIND_BY_KEYS}, {@see \Cycle\ORM\SchemaInterface::TYPECAST} and
 * {@see \Cycle\ORM\SchemaInterface::GENERATED_FIELDS} are FIELD names (the keys of `COLUMNS`),
 * NOT the database column names. Using a column name (`parent_id`) instead of the field
 * (`parentId`) lets INSERTs succeed but breaks reads with `Undefined array key ...` during result
 * parsing, because the parser keys rows by field name.
 *
 * @see Entity\Event The mapped entity.
 * @see \Cycle\ORM\Tests\Functional\Driver\Postgres\Integration\Case8\CaseTest
 *      The PostgreSQL variant that runs the same assertions against a real RANGE-partitioned table.
 */
#[DontGenerateAttribute]
abstract class CaseTest extends BaseTest
{
    use IntegrationTestTrait;
    use TableTrait;

    /** Two UUID7 values sharing the same time prefix — i.e. the same logical "parent" / partition. */
    private const PARENT_A = '0191b6e0-0000-7000-8000-000000000001';
    private const PARENT_B = '0191b6e0-0000-7000-8000-000000000002';

    /**
     * A freshly created entity has no `id` (it is `null`); after persisting, the database-generated
     * value of the `id` part of the composite key is read back into the entity via `RETURNING`.
     */
    public function testCreateGeneratesIdFromDatabase(): void
    {
        $event = new Event(self::PARENT_A, 'first');
        $this->assertNull($event->id);

        $this->save($event);

        // The `id` part of the composite PK has been generated by the database and read back.
        $this->assertIsInt($event->id);
        $this->assertGreaterThan(0, $event->id);
    }

    /**
     * Two entities sharing the same `parent_id` (the same partition) still receive distinct `id`
     * values — the autoincrement sequence is global to the table, not per-parent, so the composite
     * keys `(parent_id, id)` do not collide.
     */
    public function testSiblingsUnderSameParentGetDistinctIds(): void
    {
        $a = new Event(self::PARENT_A, 'a');
        $b = new Event(self::PARENT_A, 'b');

        $this->save($a, $b);

        $this->assertIsInt($a->id);
        $this->assertIsInt($b->id);
        $this->assertNotSame($a->id, $b->id);
    }

    /**
     * After persisting, the row can be loaded back by its full composite key. The heap is reset
     * first so the entity is actually re-read from the database (and not served from the identity
     * map), which also exercises result parsing keyed by field name — the place that breaks if
     * {@see \Cycle\ORM\SchemaInterface::PRIMARY_KEY} lists column names instead of field names.
     *
     * The argument to {@see \Cycle\ORM\Select::wherePK()} is ordered to match `PRIMARY_KEY`
     * (`['parentId', 'id']`): `parent_id` first, then `id`.
     */
    public function testFetchByCompositePk(): void
    {
        $event = new Event(self::PARENT_B, 'payload-b');
        $this->save($event);

        // Drop the heap to force a real round-trip to the database.
        $this->orm = $this->orm->withHeap(new Heap());

        $found = (new Select($this->orm, Event::class))
            ->wherePK([self::PARENT_B, $event->id]) // order matches Schema::PRIMARY_KEY
            ->fetchOne();

        $this->assertInstanceOf(Event::class, $found);
        $this->assertSame(self::PARENT_B, $found->parentId);
        $this->assertSame($event->id, $found->id);
        $this->assertSame('payload-b', $found->payload);
    }

    /**
     * Builds the table and loads the schema. The case self-skips on drivers that cannot return a
     * generated value for a composite key (no `RETURNING` support) — see the class docblock.
     */
    public function setUp(): void
    {
        parent::setUp();

        // The generated value of a composite key can only be returned by drivers supporting RETURNING.
        if (!\in_array(static::DRIVER, ['postgres', 'sqlserver'], true)) {
            $this->markTestSkipped(\sprintf('Driver `%s` does not support RETURNING.', static::DRIVER));
        }

        $this->createEventTable();

        $this->loadSchema(__DIR__ . '/schema.php');
    }

    /**
     * Create the `event` table with a composite PK `(parent_id, id)`, where `id` is a database
     * autoincrement. Portable (non-partitioned) version; drivers may override it, e.g. Postgres
     * creates a real partitioned table to exercise partitioning.
     */
    protected function createEventTable(): void
    {
        $this->makeTable('event', [
            'parent_id' => 'string',     // UUID7 stored as a string (cross-driver-safe idiom, see Case318)
            'id' => 'bigPrimary',        // database autoincrement (bigserial / IDENTITY)
            'payload' => 'string,nullable',
        ], pk: ['parent_id', 'id']);
    }
}
