<?php

declare(strict_types=1);

namespace Cycle\ORM\Tests\Functional\Driver\Common\Integration\Case8\Entity;

/**
 * Entity with a composite primary key (parent_id, id) where one part is generated by the database.
 *
 *  - $parentId — UUID (UUID7, time-ordered) supplied by the application. On the database side it is
 *    meant to be the partitioning key, therefore it has to be a part of the primary key.
 *  - $id — generated by the database (bigserial / IDENTITY) and read back after insert via RETURNING.
 */
class Event
{
    /** Database-generated part of the composite PK. */
    public ?int $id = null;

    public function __construct(
        /** Application-supplied part of the composite PK (UUID7, partition key). */
        public string $parentId,
        public ?string $payload = null,
    ) {}
}
